services:
  omnirest:
    build: .
    container_name: omnirest_app
    ports:
      - "8080:8080"
    volumes:
      - ./omnirest_data:/app/data # datos + token de Google guardado aquí
    environment:
      - NODE_ENV=production
      - DATA_PATH=/app/data
      - TOKEN_PATH=/app/data/google_token.json
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    restart: unless-stopped
